/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiPBO;

import back.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rayri
 */
public class hlmDaftarMahasiswa extends javax.swing.JFrame {
    dbRegisteredAccount ra;
    dbMahasiswa dbmhs;
    DefaultTableModel modelMahasiswa;
    UserOnAction User;
    /**
     * Creates new form hlmDaftarMahasiswa
     */
    public hlmDaftarMahasiswa(UserOnAction User, dbMahasiswa dbmhs, dbRegisteredAccount ra) {
        initComponents();
        this.ra = ra;
        this.dbmhs = dbmhs;
        this.User = User;
    }
    
    public void viewTable(){
        String[] namaKolom = {"NPM", "Nama", "Prodi", "Kelas", "Status", "Angkatan"};
        Object[][] objekmahasiswa = new Object[dbmhs.getALL().size()][6];
        String Prodi = (String) cbProdi.getSelectedItem();
        String Angkatan = (String) cbAngkatan.getSelectedItem();
        String Kelas = (String) cbKelas.getSelectedItem();
        int i = 0;
        for(Mahasiswa mhs:dbmhs.getALL()){
            if(mhs.getProdi().equals(Prodi) && mhs.getAngkatan().equals(Angkatan) && mhs.getKelas().equalsIgnoreCase(Kelas)){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++; 
            }else if(cbProdi.getSelectedItem().equals("All") && cbAngkatan.getSelectedItem().equals("All") && cbKelas.getSelectedItem().equals("All")){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++;
            }else if(mhs.getProdi().equals(Prodi) && cbAngkatan.getSelectedItem().equals("All") && cbKelas.getSelectedItem().equals("All")){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++;
            }else if(cbProdi.getSelectedItem().equals("All") && mhs.getAngkatan().equals(Angkatan) && cbKelas.getSelectedItem().equals("All")){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++;
            }else if(cbProdi.getSelectedItem().equals("All") && cbAngkatan.getSelectedItem().equals("All") && mhs.getKelas().equals(Kelas)){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++;
            }else if(mhs.getProdi().equals(Prodi) && mhs.getAngkatan().equals(Angkatan) && cbKelas.getSelectedItem().equals("All")){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++;
            }else if(mhs.getProdi().equals(Prodi) && cbAngkatan.getSelectedItem().equals("All") && mhs.getKelas().equalsIgnoreCase(Kelas)){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++;
            }else if(cbProdi.getSelectedItem().equals("All") && mhs.getAngkatan().equals(Angkatan) && mhs.getKelas().equalsIgnoreCase(Kelas)){
                String arrayMahasiswa[] = {mhs.getNpm(), mhs.getNama(), mhs.getProdi(), mhs.getKelas(), mhs.getStatus(), mhs.getAngkatan()};
                objekmahasiswa[i] = arrayMahasiswa;
                i++;
            }
        }
        modelMahasiswa = new DefaultTableModel(objekmahasiswa, namaKolom);
        tbDaftarMahasiswa.setModel(modelMahasiswa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDaftarMahasiswa = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        cbProdi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbAngkatan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbKelas = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR MAHASISWA");

        tbDaftarMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NPM", "Nama", "Prodi", "Kelas", "Status", "Angkatan"
            }
        ));
        tbDaftarMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbDaftarMahasiswa);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        cbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "All" }));

        jLabel2.setText("Prodi");

        jLabel3.setText("Angkatan");

        cbAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "All" }));

        jLabel4.setText("Kelas");

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "All" }));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnCari))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new hlmMenu(User, dbmhs, ra).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        viewTable();
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbAngkatan;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDaftarMahasiswa;
    // End of variables declaration//GEN-END:variables
}
